### ISSUE TITLE
Unable to Complete Setup on OPNsense

### ISSUE THREAD

**Issue by adam8833** [lilchancep/att-pfsense-ipv6#2]
I'm running OPNsense and was trying to use the guide to set it up.  However there are some differences that I'm having issues with.  Is it possible to get a OPNsense branch set up with instructions and/or screenshots? 

Nevermind:  Cancel this.  It turns out that with OPNsense, I don't need to do any of this.  I just simply have to assign a different IPv6 Prefix ID to each VLAN and the appropriate IPv6 allow rules and it works great!

**Comment by CaskAle** [comment]
What did you use as prexix ids?

**Comment by CaskAle** [comment]
Thats great.  At least it gives me hope.  I am unable to do the same but i shall persevere.  If you don't mind me asking, who is your service provider.  AT&T for me.

**Comment by adam8833** [comment]
I'm using AT&T Fiber. I've bypassed the AT&T equipment on OPNsense using https://github.com/zombielinux/pfatt

**Comment by lilchancep** [comment]
This method assumes that you are using the ATT hardware. I have not tested it with the supplicant method. 

I used to use the bypass however att now issues new equipment that you are no longer able to bypass
