### ISSUE TITLE
Additional RG/Firmware Information

### ISSUE THREAD

**Issue by strangefello** [lilchancep/att-pfsense-ipv6#3]
Howdy,

Apologies if this is not the correct way to submit this.  I have a HUMAX BGW320-500 running firmware 3.19.5.  The state table also shows a maximum of 8192 sessions.  Thanks for making this guide!

![22-10-04T12-27-02_FFvQR5TgQZ](https://user-images.githubusercontent.com/25989973/193886343-36192041-6823-481e-94f8-318579e5e96e.png)

![22-10-04T12-27-12_vivaldi_GayVJdxpaO](https://user-images.githubusercontent.com/25989973/193886341-03b0a28a-67fc-4526-bd95-2877d6e9cdb2.png)

**Comment by lilchancep** [comment]
I made sure this information was present, thank you!
